name: Run jaffle_shop_pipeline pipeline from jaffle_shop_pipeline.py
'on':
  schedule:
  - cron: '*/30 * * * *'
  workflow_dispatch: null
env:
  EXTRACT__WORKERS: '5'
  DATA_WRITER__BUFFER_MAX_ITEMS: '5000'
  NORMALIZE__WORKERS: '1'
  NORMALIZE__DATA_WRITER__FILE_MAX_ITEMS: '1000'
  LOAD__WORKERS: '5'
jobs:
  maybe_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: always
        skip_after_successful_duplicate: 'false'
        do_not_skip: '[]'
  run_pipeline:
    needs: maybe_skip
    if: needs.maybe_skip.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements_github_action.txt
    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - run: pip install -r requirements_github_action.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - name: Run pipeline script
      run: python 'jaffle_shop_pipeline.py'
